### ISSUE TITLE
What GPUs have you used for training the Monodepth2

### ISSUE THREAD

**Issue by wuyujack** [nianticlabs/monodepth2#41] opened 2019-07-10 09:15 UTC
Hi, 

Thank you for sharing the code and one question for the GPU version you used. I use RTX 2080 Ti and seems like there are issues:

> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1544174967633/work/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    trainer.train()
  File "/home/mingfu/monodepth2/trainer.py", line 186, in train
    self.run_epoch()
  File "/home/mingfu/monodepth2/trainer.py", line 202, in run_epoch
    outputs, losses = self.process_batch(inputs)
  File "/home/mingfu/monodepth2/trainer.py", line 252, in process_batch
    outputs.update(self.predict_poses(inputs, features))
  File "/home/mingfu/monodepth2/trainer.py", line 292, in predict_poses
    axisangle[:, 0], translation[:, 0], invert=(f_i < 0))
  File "/home/mingfu/monodepth2/layers.py", line 41, in transformation_from_parameters
    M = torch.matmul(R, T)
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1544174967633/work/aten/src/THC/THCBlas.cu:441

However, when I change to V100, the code works.

**Comment by daniyar-niantic** [comment] 2019-07-10 09:19
Hi @wuyujack 

I suspect that the issue is due to CUDA and cuDNN versions and possibly pytorch version. Could you check the versions that you are using for RTX 2080 Ti and V100?

Thanks!

**Comment by mdfirman** [comment] 2019-07-10 09:28
Agreed, looks related to this: https://github.com/pytorch/pytorch/issues/12977

It would be useful for know if you are able to run any pytorch code on the RTX? What about a simple program which uses the offending `torch.matmul`? e.g.

```
import torch
a = torch.rand(3, 3)
b = torch.rand(3, 3)
torch.matmul(a, b)
```
If either of these fail then I think the problem is outside of our scope.

**Comment by wuyujack** [comment] 2019-07-10 09:29
> Hi @wuyujack
> 
> I suspect that the issue is due to CUDA and cuDNN versions and possibly pytorch version. Could you check the versions that you are using for RTX 2080 Ti and V100?
> 
> Thanks!

 Thank you for your quick reply. For RTX 2080 Ti and V100 I both used cudatoolkit 9.0 (installed by conda) and py3.6_cuda9.0.176_cudnn7.4.1_1 and cudnn 7.6.0 (also installed by conda).  Now I am trying to match all of them and also try the cudatoolkit 10 for luck : )

**Comment by wuyujack** [comment] 2019-07-10 09:30
> Agreed, looks related to this: [pytorch/pytorch#12977](https://github.com/pytorch/pytorch/issues/12977)
> 
> It would be useful for know if you are able to run any pytorch code on the RTX? What about a simple program which uses the offending `torch.matmul`? e.g.
> 
> ```
> import torch
> a = torch.rand(3, 3)
> b = torch.rand(3, 3)
> torch.matmul(a, b)
> ```
> 
> If either of these fail then I think the problem is outside of our scope.

Also thank you for your quick reply! I will try and let you know in case that others can save their time to avoid using the RTX 2080 Ti if it doesn't work : )

**Comment by wuyujack** [comment] 2019-07-10 09:56
@daniyar-niantic @mdfirman Finally it works when I turn to cudatoolkit 10 (installed by conda) and also change the cudnn version and pytorch version correspondingly : ) 

My experiment environment for RTX2080 Ti is: 

> Package                        Version
   cudnn:                             7.6.0
   cudatoolkit:                     10.0.130
   pytorch:                           1.1.0                   (Build: py3.6_cuda10.0.130_cudnn7.5.1_0)
   tensorboardx:                  1.8

**Comment by mdfirman** [comment] 2019-07-10 10:13
Super, thank you! I will close this issue now.

**Closed by mdfirman** 2019-07-10 10:13 UTC
